# Generated by Django 2.2.3 on 2019-07-16 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sallary',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='position',
            name='salary_max',
            field=models.IntegerField(default=1, verbose_name=django.core.validators.MinValueValidator(models.IntegerField(default=0))),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_left',
            field=models.IntegerField(default=20),
        ),
    ]
