# Generated by Django 2.2.5 on 2019-10-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190716_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='position',
            name='salary_min',
        ),
    ]
